# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 王启蒙的博客
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/wqm17.github.io" # the subpath of the site
url: "https://wqm17.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: 主页
      slug: /
    - name: 学习笔记
    - name: 个人博客

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: wqm17@foxmail.com
      link: mailto:wqm17@foxmail.com
    - name: WeChat
      value: A_Man_From_Earth
      link: "#"
  follow:
    - name: Weibo
      link: https://weibo.com/u/3859616034
      username: "@巴扎那个黑那个嘿嘿嘿"
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
